name: mc2hessian
dependencies:
- fastcache=1.0.2=py27_0
- numpy=1.9.2=py27_0
- openssl=1.0.1k=1
- pandas=0.16.0=np19py27_1
- pip=6.1.1=py27_0
- python=2.7.9=3
- python-dateutil=2.4.2=py27_0
- pytz=2015.2=py27_0
- readline=6.2=2
- setuptools=15.2=py27_0
- six=1.9.0=py27_0
- sqlite=3.8.4.1=1
- system=5.8=2
- tk=8.5.18=0
- zlib=1.2.8=0
- pip:
  - tabulate==0.7.4

